[book]
title = "Seal Rust SDK Guide"
author = ["Quentin Diebold"]
description = "Developer guide and reference for the seal-sdk-rs crate"
language = "en"
multilingual = false
src = "src"

[output.html]
fold.enable = true

[preprocessor.links]
