[book]
title = "Seal Rust SDK Guide"
authors = ["Quentin Diebold <pro@quentindiebold.com>"]
description = "Developer guide and reference for the seal-sdk-rs crate"
language = "en"
src = "src"

[output.html]
fold.enable = true

[preprocessor.links]
