name: CI Checks

on:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run clippy (all targets, tests)
        run: cargo clippy --all-targets --all-features -- -D warnings

  tests:
    runs-on: ubuntu-latest
    needs: clippy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install mdBook
        run: cargo install mdbook --locked

      - name: Build documentation
        run: mdbook build book

      - name: Build test images
        run: ./build_test_images.sh

      - name: Run tests
        run: cargo test --all-features
