name: Publish crate

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout release target
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}
          fetch-depth: 0

      - name: Configure git user
        run: |
          git config --global user.email "pro@quentindiebold.com"
          git config --global user.name "Quentin Diebold (CI)"

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install mdBook
        run: cargo install mdbook --locked

      - name: Install licensesnip
        run: cargo install licensesnip --locked

      - name: Build documentation
        run: mdbook build book --dest-dir ../docs

      - name: License
        run: licensesnip

      - name: Run clippy (all targets, tests)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build test images
        run: ./build_test_images.sh

      - name: Run tests
        run: cargo test --all-features

      - name: Push updated files
        run: |
          git add .
          git commit -m "chore(ci): publish release"
          git push
